"""Bonus + Deduction — the building blocks plugged into salary computation.

Bonuses can be:
- KPI         (auto, generated by the KPI engine)
- FIXED       (manual, e.g. holiday bonus)
- OVERTIME    (auto, computed from attendance overtime_minutes)
- PROJECT     (manual, ad-hoc)

Deductions can be:
- LATE        (auto, late minutes × penalty rate from company.settings)
- ABSENCE     (auto, no check-in on a working day)
- PENALTY     (manual)
- TAX         (manual or external)
- ADVANCE     (manual, mirrors a SalaryTransaction)
"""
from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal
from enum import StrEnum
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Numeric, String
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TenantMixin, TimestampMixin

if TYPE_CHECKING:
    pass


class BonusType(StrEnum):
    KPI = "KPI"
    FIXED = "FIXED"
    OVERTIME = "OVERTIME"
    PROJECT = "PROJECT"


class DeductionType(StrEnum):
    LATE = "LATE"
    ABSENCE = "ABSENCE"
    PENALTY = "PENALTY"
    TAX = "TAX"
    ADVANCE = "ADVANCE"


class Bonus(Base, TenantMixin, TimestampMixin):
    __tablename__ = "bonuses"

    employee_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("employees.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    period_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("salary_periods.id", ondelete="SET NULL"),
        index=True,
    )

    type: Mapped[BonusType] = mapped_column(String(16), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)
    reason: Mapped[str | None] = mapped_column(String(500))
    given_by: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )

    applied_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    applied_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    auto_generated: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)


class Deduction(Base, TenantMixin, TimestampMixin):
    __tablename__ = "deductions"

    employee_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("employees.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    period_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("salary_periods.id", ondelete="SET NULL"),
        index=True,
    )

    type: Mapped[DeductionType] = mapped_column(String(16), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)
    reason: Mapped[str | None] = mapped_column(String(500))
    applied_by: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )

    applied_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    applied_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    auto_generated: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
