"""leave_adjustment_table

Revision ID: ffe729b1a2f1
Revises: a8646b2fc394
Create Date: 2026-04-30 02:26:11.920214

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe729b1a2f1'
down_revision: Union[str, None] = 'a8646b2fc394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_adjustments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('days_delta', sa.Integer(), nullable=False),
    sa.Column('amount_delta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_adjustments_company_id'), 'leave_adjustments', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_adjustments_employee_id'), 'leave_adjustments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_adjustments_leave_type_id'), 'leave_adjustments', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_adjustments_year'), 'leave_adjustments', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_adjustments_year'), table_name='leave_adjustments')
    op.drop_index(op.f('ix_leave_adjustments_leave_type_id'), table_name='leave_adjustments')
    op.drop_index(op.f('ix_leave_adjustments_employee_id'), table_name='leave_adjustments')
    op.drop_index(op.f('ix_leave_adjustments_company_id'), table_name='leave_adjustments')
    op.drop_table('leave_adjustments')
    # ### end Alembic commands ###
