"""employee_extra_fields

Revision ID: 70c4db94798d
Revises: 611777f06d0d
Create Date: 2026-04-29 18:42:37.926693

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c4db94798d'
down_revision: Union[str, None] = '611777f06d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('gender', sa.String(length=8), nullable=True))
    op.add_column('employees', sa.Column('inn', sa.String(length=32), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_name', sa.String(length=200), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_relation', sa.String(length=64), nullable=True))
    op.add_column('employees', sa.Column('bank_card_number', sa.String(length=32), nullable=True))
    op.add_column('employees', sa.Column('bank_name', sa.String(length=120), nullable=True))
    op.add_column('employees', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'notes')
    op.drop_column('employees', 'bank_name')
    op.drop_column('employees', 'bank_card_number')
    op.drop_column('employees', 'emergency_contact_relation')
    op.drop_column('employees', 'emergency_contact_phone')
    op.drop_column('employees', 'emergency_contact_name')
    op.drop_column('employees', 'inn')
    op.drop_column('employees', 'gender')
    # ### end Alembic commands ###
