"""branch_photo_url

Revision ID: 611777f06d0d
Revises: 1c57a4a679b7
Create Date: 2026-04-29 18:13:30.040225

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611777f06d0d'
down_revision: Union[str, None] = '1c57a4a679b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'photo_url')
    # ### end Alembic commands ###
