"""salary kpi leave bonus deduction

Revision ID: 9f731a824c77
Revises: a41f7e1874a9
Create Date: 2026-04-28 11:03:34.786458

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f731a824c77'
down_revision: Union[str, None] = 'a41f7e1874a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('metric_source', sa.String(length=8), nullable=False),
    sa.Column('formula', sa.String(length=500), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reward_type', sa.String(length=20), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_kpi_templates_company_name')
    )
    op.create_index(op.f('ix_kpi_templates_company_id'), 'kpi_templates', ['company_id'], unique=False)
    op.create_table('leave_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('max_days_per_year', sa.Integer(), nullable=True),
    sa.Column('requires_document', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_leave_types_company_name')
    )
    op.create_index(op.f('ix_leave_types_company_id'), 'leave_types', ['company_id'], unique=False)
    op.create_table('kpi_assignments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('kpi_template_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('target', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('computed_reward', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kpi_template_id'], ['kpi_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'kpi_template_id', 'year', 'month', name='uq_kpi_assignments_emp_tpl_year_month')
    )
    op.create_index(op.f('ix_kpi_assignments_company_id'), 'kpi_assignments', ['company_id'], unique=False)
    op.create_index(op.f('ix_kpi_assignments_employee_id'), 'kpi_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_kpi_assignments_kpi_template_id'), 'kpi_assignments', ['kpi_template_id'], unique=False)
    op.create_table('kpi_data_points',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_data_points_company_id'), 'kpi_data_points', ['company_id'], unique=False)
    op.create_index(op.f('ix_kpi_data_points_employee_id'), 'kpi_data_points', ['employee_id'], unique=False)
    op.create_index(op.f('ix_kpi_data_points_metric_key'), 'kpi_data_points', ['metric_key'], unique=False)
    op.create_table('leave_requests',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_company_id'), 'leave_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_end_date'), 'leave_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_leave_type_id'), 'leave_requests', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_start_date'), 'leave_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_table('salary_daily_accruals',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('base_earned', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('overtime_earned', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bonuses_earned', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('kpi_earned', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_salary_daily_accruals_emp_date')
    )
    op.create_index(op.f('ix_salary_daily_accruals_company_id'), 'salary_daily_accruals', ['company_id'], unique=False)
    op.create_index(op.f('ix_salary_daily_accruals_date'), 'salary_daily_accruals', ['date'], unique=False)
    op.create_index(op.f('ix_salary_daily_accruals_employee_id'), 'salary_daily_accruals', ['employee_id'], unique=False)
    op.create_table('salary_periods',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bonuses_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductions_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('overtime_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('kpi_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month', name='uq_salary_periods_emp_year_month')
    )
    op.create_index(op.f('ix_salary_periods_company_id'), 'salary_periods', ['company_id'], unique=False)
    op.create_index(op.f('ix_salary_periods_employee_id'), 'salary_periods', ['employee_id'], unique=False)
    op.create_table('bonuses',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('given_by', sa.UUID(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['given_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['salary_periods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonuses_applied_date'), 'bonuses', ['applied_date'], unique=False)
    op.create_index(op.f('ix_bonuses_company_id'), 'bonuses', ['company_id'], unique=False)
    op.create_index(op.f('ix_bonuses_employee_id'), 'bonuses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_bonuses_period_id'), 'bonuses', ['period_id'], unique=False)
    op.create_table('deductions',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('applied_by', sa.UUID(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['salary_periods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deductions_applied_date'), 'deductions', ['applied_date'], unique=False)
    op.create_index(op.f('ix_deductions_company_id'), 'deductions', ['company_id'], unique=False)
    op.create_index(op.f('ix_deductions_employee_id'), 'deductions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_deductions_period_id'), 'deductions', ['period_id'], unique=False)
    op.create_table('salary_transactions',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['salary_periods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_transactions_company_id'), 'salary_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_salary_transactions_employee_id'), 'salary_transactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salary_transactions_period_id'), 'salary_transactions', ['period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_transactions_period_id'), table_name='salary_transactions')
    op.drop_index(op.f('ix_salary_transactions_employee_id'), table_name='salary_transactions')
    op.drop_index(op.f('ix_salary_transactions_company_id'), table_name='salary_transactions')
    op.drop_table('salary_transactions')
    op.drop_index(op.f('ix_deductions_period_id'), table_name='deductions')
    op.drop_index(op.f('ix_deductions_employee_id'), table_name='deductions')
    op.drop_index(op.f('ix_deductions_company_id'), table_name='deductions')
    op.drop_index(op.f('ix_deductions_applied_date'), table_name='deductions')
    op.drop_table('deductions')
    op.drop_index(op.f('ix_bonuses_period_id'), table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_employee_id'), table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_company_id'), table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_applied_date'), table_name='bonuses')
    op.drop_table('bonuses')
    op.drop_index(op.f('ix_salary_periods_employee_id'), table_name='salary_periods')
    op.drop_index(op.f('ix_salary_periods_company_id'), table_name='salary_periods')
    op.drop_table('salary_periods')
    op.drop_index(op.f('ix_salary_daily_accruals_employee_id'), table_name='salary_daily_accruals')
    op.drop_index(op.f('ix_salary_daily_accruals_date'), table_name='salary_daily_accruals')
    op.drop_index(op.f('ix_salary_daily_accruals_company_id'), table_name='salary_daily_accruals')
    op.drop_table('salary_daily_accruals')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_start_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_leave_type_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_end_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_company_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_kpi_data_points_metric_key'), table_name='kpi_data_points')
    op.drop_index(op.f('ix_kpi_data_points_employee_id'), table_name='kpi_data_points')
    op.drop_index(op.f('ix_kpi_data_points_company_id'), table_name='kpi_data_points')
    op.drop_table('kpi_data_points')
    op.drop_index(op.f('ix_kpi_assignments_kpi_template_id'), table_name='kpi_assignments')
    op.drop_index(op.f('ix_kpi_assignments_employee_id'), table_name='kpi_assignments')
    op.drop_index(op.f('ix_kpi_assignments_company_id'), table_name='kpi_assignments')
    op.drop_table('kpi_assignments')
    op.drop_index(op.f('ix_leave_types_company_id'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_kpi_templates_company_id'), table_name='kpi_templates')
    op.drop_table('kpi_templates')
    # ### end Alembic commands ###
