"""leave_override_amount

Revision ID: a8646b2fc394
Revises: 70c4db94798d
Create Date: 2026-04-30 01:35:11.337361

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8646b2fc394'
down_revision: Union[str, None] = '70c4db94798d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('override_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'override_amount')
    # ### end Alembic commands ###
