"""employees shifts attendance

Revision ID: a41f7e1874a9
Revises: 32fb111bde1a
Create Date: 2026-04-27 19:55:48.063094

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41f7e1874a9'
down_revision: Union[str, None] = '32fb111bde1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('expected_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('allow_overtime', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_shift_templates_company_name')
    )
    op.create_index(op.f('ix_shift_templates_company_id'), 'shift_templates', ['company_id'], unique=False)
    op.create_table('employees',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('employee_code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('passport', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('work_type', sa.String(length=16), nullable=False),
    sa.Column('shift_template_id', sa.UUID(), nullable=True),
    sa.Column('salary_type', sa.String(length=16), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('overtime_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('face_template_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_code', name='uq_employees_company_code')
    )
    op.create_index(op.f('ix_employees_branch_id'), 'employees', ['branch_id'], unique=False)
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=False)
    op.create_index(op.f('ix_employees_shift_template_id'), 'employees', ['shift_template_id'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_table('attendance_records',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('check_type', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('selfie_url', sa.String(length=500), nullable=True),
    sa.Column('face_match_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('is_early_leave', sa.Boolean(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_branch_id'), 'attendance_records', ['branch_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_company_id'), 'attendance_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_device_id'), 'attendance_records', ['device_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_status'), 'attendance_records', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_records_timestamp'), 'attendance_records', ['timestamp'], unique=False)
    op.create_table('flexible_configs',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('min_daily_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_daily_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('required_weekly_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('core_hours_start', sa.Time(), nullable=True),
    sa.Column('core_hours_end', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', name='uq_flexible_configs_employee')
    )
    op.create_index(op.f('ix_flexible_configs_company_id'), 'flexible_configs', ['company_id'], unique=False)
    op.create_index(op.f('ix_flexible_configs_employee_id'), 'flexible_configs', ['employee_id'], unique=False)
    op.create_table('shift_schedules',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_template_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('custom_start', sa.Time(), nullable=True),
    sa.Column('custom_end', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_shift_schedules_employee_date')
    )
    op.create_index(op.f('ix_shift_schedules_company_id'), 'shift_schedules', ['company_id'], unique=False)
    op.create_index(op.f('ix_shift_schedules_date'), 'shift_schedules', ['date'], unique=False)
    op.create_index(op.f('ix_shift_schedules_employee_id'), 'shift_schedules', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shift_schedules_shift_template_id'), 'shift_schedules', ['shift_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_schedules_shift_template_id'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_employee_id'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_date'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_company_id'), table_name='shift_schedules')
    op.drop_table('shift_schedules')
    op.drop_index(op.f('ix_flexible_configs_employee_id'), table_name='flexible_configs')
    op.drop_index(op.f('ix_flexible_configs_company_id'), table_name='flexible_configs')
    op.drop_table('flexible_configs')
    op.drop_index(op.f('ix_attendance_records_timestamp'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_status'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_device_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_company_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_branch_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_shift_template_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_branch_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_shift_templates_company_id'), table_name='shift_templates')
    op.drop_table('shift_templates')
    # ### end Alembic commands ###
